name: Analyze Commit with Gemini AI

on:
  push:
    branches:
      - main
      - develop

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # garante que HEAD~1 exista

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: pip install requests python-dotenv

      # 4️⃣ Rodar análise
      - name: Run commit analysis
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}          # Token de Service Account Vertex AI
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}# ID do projeto GCP
          GOOGLE_LOCATION: ${{ secrets.GOOGLE_LOCATION }}    # opcional, default: us-central1
          GH_TOKEN: ${{ secrets.GH_PAT }}                   # GitHub token para criar issues automaticamente
        run: python scripts/analyze_diff.py
