name: Analyze Commit with AI

on:
  push:
    branches:
      - main
      - develop

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write # Permissão necessária para criar issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Garante que o commit anterior (HEAD~1) esteja disponível

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv google-auth

      - name: Run Analysis and Create Issue
        env:
          # O secret deve ser o CONTEÚDO do JSON da sua service account, não o caminho para o arquivo.
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/analyze_diff.py
